// <auto-generated />
namespace Inventory_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Feb2121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feb2121));
        
        string IMigrationMetadata.Id
        {
            get { return "202102211752422_Feb2121"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
