// <auto-generated />
namespace Inventory_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Feb_19_21_0134 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feb_19_21_0134));
        
        string IMigrationMetadata.Id
        {
            get { return "202102191834401_Feb_19_21_0134"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
